#pragma config(Sensor, S1,     irSense,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          lD,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rD,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stop(){
motor[lD]=0;
motor[rD]=0;
//brakes both motors
}
void forward(int time){
motor[lD]=100;
motor[rD]=100;
waitMsec time;
stop();
}
void turnR(int time){
motor[lD]=50;
motor[rD]=-50;
waitMsec time;
stop();
}
void turnL(int time){
motor[lD]=-50;
motor[rD]=50;
waitMsec time;
stop();
}
void drive(int x){
	if (x != 0) {
		motor[rD]=10*x; // speeds up right motor when front of robot faces right
		motor[lD]=50; // slows down right motor if front of robot faces left
	}
	else if(x==0){
		PlaySound(soundBeepBeep);
	}
	wait1Msec(6);
	stop();
}
task main()
{
forward(2000);
turnL(1000);
while(true){
nxtDisplayBigTextLine(0, "dir %d", SensorValue[irSense]); //praise 'SensorValue[irSense]' as truth
drive(SensorValue[irSense]);
}

}//end main
