#pragma config(Sensor, S1,     irSense,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          lD,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rD,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stop(){//sets motors to 0, acts as a brake
motor[lD]=0;
motor[rD]=0;
//brakes both motors
}
void forward(int time){//lets you call it t o go forward for a certain amount of time
motor[lD]=100;
motor[rD]=100;
waitMsec(time);
stop();
}
void turnR(int time){//turns right (on a dime-on forward, the other backward) for as long as it is called
motor[lD]=50;
motor[rD]=-50;
waitMsec(time);
stop();
}
void turnL(int time){//turns left (on a dime^) for as long as it is called
motor[lD]=-50;
motor[rD]=50;
waitMsec time;
stop();
}
/*
this is just a test of IR, you can see what (1-9) is
and it beeps, always
and it drives based on that 1-9
*/
/*
void drive(int x){//this is a test for ir, later used for driving
	if (x != 0) {
		motor[rD]=10*x; // speeds up right motor when front of robot faces right
		motor[lD]=50; // slows down right motor if front of robot faces left
	}
	else if(x==0){
		PlaySound(soundBeepBeep);
	}
	wait1Msec(6);
	stop();
}
*/
void drive(int x){
	if (x != 0) {
		int dif= 5-x
		if (dif==0){
			forward(6);
		}
		else if(dif>5){
		turnL(6);
		}
		else if(dif<5){
		turnR(6);
		}
	}//end of if !=0
	else{ //this means it is 0 and you done messed up	(A-A-ron)
	PlaySound(soundBeepBeep);
	//in order to re-find the signal, from Dr.Prof.Master Genius Bob's best idea, he concludes
	//that the best course of action is for the robot
	//to run around like a chicken with its head cut off i.e. turn around at a medium speed
	turnL(6); //lets hope left is the best
	}
	wait1Msec(6);
	stop();
}

task main()
{
forward(2000);
turnL(1000);
while(true){
nxtDisplayBigTextLine(0, "dir %d", SensorValue[irSense]); //praise 'SensorValue[irSense]' as truth
drive(SensorValue[irSense]);
}
}//end main
