#pragma config(Sensor, S1,     irSense,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          lD,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rD,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

void initializeRobot(){
	return;
}
void stop(){
motor[lD]=0;
motor[rD]=0;
//brakes both motors
}
void forward(int time){ //lets you call it t o go forward for a certain amount of time
motor[lD]=100;
motor[rD]=100;
wait1Msec(time);
stop();
}
void backward(int time){ //lets you call it to go forward for a certain amount of time
motor[lD]=-75;
motor[rD]=-75;
wait1Msec(time);
stop();
}
void turnR(int time){ //turns right (on a dime-on forward, the other backward) for as long as it is called
motor[lD]=50;
motor[rD]=-50;
wait1Msec(time);
stop();
}
void drive(int x){
	if (x != 0) {
		motor[rD]=10+(10*x); // if robot faces right (x value >5) right motor speeds up
		motor[lD]=60; // if robot faces left (x value >0 and <5) right motor slows down
	}
	else if(x==0){
	//	PlaySound(soundBeepBeep);
	}
	wait1Msec(6);
	stop();
}
task main()
{
	initializeRobot();
	//waitForStart();
while(true){
	nxtDisplayBigTextLine(0, "dir %d", SensorValue[irSense]); //praise 'SensorValue[irSense]' as truth
drive(SensorValue[irSense]);
}

}//end main
