#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheel1,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel2,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_1,     leftWheel1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     leftWheel2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    backGrab,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    frontGrab,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define backDown 250
#define backUp 125
#define frontDown 200
#define frontUp 0

void flagSpin(int time)
{
motor[flag] = 50;
wait1Msec(time);
motor[flag]=0;
}

task main()
{
	int modifier = 1;//set modifier variable
	//initializeRobot();
	while(true)
	{
		getJoystickSettings(joystick); //gets joystick input
		if(joy1Btn(6))
		{ //This creates a modifier variable. When the assistant driver presses the upper right trigger,
			//the robot goes at a fifth of it's normal power
			modifier = 5;
		}
		else if(joy1Btn(8))
		{ //if button 8 is pressed, modifier is set to 10
			modifier = 20;
		}
		else
		{//if the buttons 6 and 8 aren't pressed, the robot goes back to driving at full power.
			modifier = 1;
		}
		if( abs(joystick.joy1_y1) > 10){
		motor[leftWheel1] = (joystick.joy1_y1 / modifier); //reads joystick values on joystick one.
		motor[leftWheel2] = (joystick.joy1_y1 / modifier);
	}
	else
	{
		motor[leftWheel1] = 0;
		motor[leftWheel2] = 0;
	}
	if( abs(joystick.joy1_y2) > 10)
	{
		motor[rightWheel1] = (joystick.joy1_y2 / modifier); //the 'y'(up and down) axis values set the power.
		motor[rightWheel2] = (joystick.joy1_y2 / modifier);
	}
	else
	{
		motor[rightWheel1] = 0;
		motor[rightWheel2] = 0;
	}

	if(joy1Btn(5)||joy2Btn(5))//change it back to joy2 after testing
	{
	servo[backGrab] = backUp;
	}
	else if(joy2Btn(7)||joy1Btn(7))//change it back to joy2 after testing
	{
	servo[backGrab] = backDown;
	}

		if(joy2Btn(6))//change it back to joy2 after testing
	{
	servo[frontGrab]=frontUp;
	}
	else if(joy2Btn(8))//change it back to joy2 after testing
	{
	servo[frontGrab]=frontDown;
	}

	if(joy2Btn(1))
	{
	flagSpin(1000);
	}
	//displays the octant the tophat is being pressed it
	/*int pos= joy1_TopHat;
	String posies="the tophat is at: " + pos;
	NxtDisplayBigStringAt(1, 1, posies);
    */
	//}
}
}
