#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheelEthan, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftWheel,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void EthanIsTheBest(int time, int turnDirection, int turnPower){
	if(turnDirection == 0){
		motor[rightWheelEthan] = turnPower;
		motor[leftWheel] = -turnPower;
		wait1Msec(time);
		motor[rightWheelEthan] = 0;
		motor[leftWheel] = 0;
	} else {
		motor[rightWheelEthan] = -turnPower;
		motor[leftWheel] = turnPower;
		wait1Msec(time);
		motor[rightWheelEthan] = 0;
		motor[leftWheel] = 0;
	}
}
/***********************************\
The above 0
\***********************************/


task main()
{
EthanIsTheBest(500, 0, -50);


}
