#pragma config(Sensor, S1,     alex,           sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define IRSEEKER IN_1

// Convenience macro that combines TextOut and NumOut
#define TextNumOut(xPos,yPos,str,col,num)  TextOut(xPos,yPos,str); \
                                           NumOut(xPos+6*col,yPos,num)

task main()
{
  int dir, s1, s2, s3, s4, s5, result;

  SetSensorLowspeed(IRSEEKER);

  while(true) {
    ReadSensorHTIRSeeker2AC(IRSEEKER, dir, s1, s2, s3, s4, s5);
    TextNumOut(0, LCD_LINE3, "Dir:    ",4,dir);
    TextNumOut(6, LCD_LINE4, "S1:     ",3,s1);
    TextNumOut(6, LCD_LINE5, "S2:     ",3,s2);
    TextNumOut(6, LCD_LINE6, "S3:     ",3,s3);
    TextNumOut(6, LCD_LINE7, "S4:     ",3,s4);
    TextNumOut(6, LCD_LINE8, "S5:     ",3,s5);
    Wait(100);
  }
  /*
  //jank/ratchet code of the year award to
  //credit to http://www.patronumbots.com/uploads/1/3/1/6/13161577/___ftc_workshop_presentation.pdf (sketchydomain@jank-city.edu)i.e.(maninthevan@notokay.com)
  //additional inspration from malwaredomainlist.com (really, these are some great guys, you should check them out and download some stuff)
  task taskLookAlive()
{
for(;;)
{
servo[servoRingLock] = RINGUNLOCKED + 10;
wait1Msec(1000);
servo[servoRingLock] = RINGUNLOCKED;
wait1Msec(1000);
}
}
//such ratchet, much skank, so unwow
*/
//end class
}
