#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S4,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int zone;//this is what of the 3 configurations the center goal is in based on ir results
	while (true)
  {
		eraseDisplay();//sum that fancy gui stuffz yum yum

  	nxtDisplayCenteredTextLine(3, "IR Value: %d", SensorValue[ir]);
  	wait10Msec(50);
	  if(SensorValue[ir] == 0){
			zone = 1;
		}else if(SensorValue[ir] == 3){
			zone = 2;
		}else if(SensorValue[ir] == 4){
			zone = 3;
		}else{
			zone = 0;
		}
  	nxtDisplayCenteredBigTextLine(6, "Zone: %d", zone);
  	wait10Msec(50);
  	//If reading 0, zone 1
	  //If reading 3, zone 2
	  //If reading 4, zone 3

  }
}
