#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This is a block comment.
*/

/*
This method will stop the motors
*/
void stopMotors(){
motor[rightDrive]=0;//this will completely halt the right drive
motor[leftDrive]=0;//this will completely halt the left drive

}

/*
This method will drive the robot forward for an amount of milliseconds equal to mTime.
*/
void forward(int mTime){

	motor[rightDrive] = 100;//this is a line comment
	motor[leftDrive] =100;
	wait1Msec(mTime);
	stopMotors();//this line stops the motors

}


/*
This method will make motors go backwards
*/
void backward(int mTime){
	motor[rightDrive] = -100;
	motor[leftDrive] = -100;
	wait1Msec(mTime);//tells how long the method is going to run
	stopMotors();//this method stops the motors
}
/*
This method will turn the robot towards the right
*/
void turn (int mTime) {
	motor[leftDrive] = 50;//gives the left motor power of 50
	motor[rightDrive] = 0;//stops the right motor
	wait1Msec (mTime);
	stopMotors ();
}
/*
because 75 is greater than 25 it ends up turning left slowly while going forward
*/
void turnAlex (int mTime)
{
	motor[leftDrive] = 25;//sets the left motor to 25
	motor[rightDrive] = 75;//sets the right motor to 75
	wait1Msec (mTime);
	stopMotors();
}


task main()
{

forward(6000);
turnAlex(6000);
turn(6000);

}
