#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     leftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_1,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot(){
	return;
}
void stop(){
motor[leftWheel]=0;
motor[rightWheel]=0;
//brakes both motors
}
void forward(int time){ //lets you call it t o go forward for a certain amount of time
motor[leftWheel]=100;
motor[rightWheel]=100;
wait1Msec(time);
stop();
}
void backward(int time){ //lets you call it to go forward for a certain amount of time
motor[leftWheel]=-75;
motor[rightWheel]=-75;
wait1Msec(time);
stop();
}
void turnR(int time){ //turns right (on a dime-on forward, the other backward) for as long as it is called
motor[leftWheel]=50;
motor[rightWheel]=-50;
wait1Msec(time);
stop();
}
void drive(int x){
	if (x != 0) {
		motor[rightWheel]=10+(10*x); // if robot faces right (x value >5) right motor speeds up
		motor[leftWheel]=60; // if robot faces left (x value >0 and <5) right motor slows down
	}
	else if(x==0){
	//	PlaySound(soundBeepBeep);
	}
	wait1Msec(6);
	stop();
}
task main()
{
	initializeRobot();
	waitForStart();
	forward(4000);
	backward(200);
	turnR(100);
while(true){
	//nxtDisplayBigTextLine(0, "dir %d", SensorValue[irSense]); //praise 'SensorValue[irSense]' as truth
//drive(SensorValue[irSense]);
}

}//end main
