#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheel1,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel2,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     leftWheel1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     leftWheel2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     Pulley,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    drop,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    back,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    back2,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define backDown 250
#define backUp 125
#define frontDown 225
#define frontUp 125


task main()
{
	waitForStart();
	int modifier = 4;//set modifier variable
	//initializeRobot();
	while(true)
	{
		getJoystickSettings(joystick); //gets joystick input
		if( abs(joystick.joy1_y1) > 10){
			motor[leftWheel1] = (-joystick.joy1_y1 / modifier); //reads joystick values on joystick one.
			motor[leftWheel2] = (-joystick.joy1_y1 / modifier);
		}
		else
		{
			motor[leftWheel1] = 0;
			motor[leftWheel2] = 0;
		}
		if( abs(joystick.joy1_y2) > 10)
		{
			motor[rightWheel1] = (-joystick.joy1_y2 / modifier); //the 'y'(up and down) axis values set the power.
			motor[rightWheel2] = (-joystick.joy1_y2 / modifier);
		}
		else
		{
			motor[rightWheel1] = 0;
			motor[rightWheel2] = 0;
		}

		if(joy1Btn(5))//change it back to joy2 after testing
		{
			servo[back] = 180;
		}
		else if(joy1Btn(7))//change it back to joy2 after testing
		{
			servo[back] = 60;
		}

		if(joy1Btn(6))
		{
			servo[back2] = 60;
		}
		else if(joy1Btn(8))
		{
			servo[back2] = 180;
		}\

		if(joy1Btn(4))
		{
			modifier = 7;
			} else if(joy1Btn(1)){
			modifier = 2;
			} else {
			modifier = 4;
		}


		if(joy2Btn(5))
		{
			motor[Pulley] = 75;
		}
		else if(joy2Btn(7))
		{
			motor[Pulley] = -75;
			}	else {
			motor[Pulley] = 0;
		}
		//Buttons 5 and 7 manipulate the lift

		if(joy2Btn(6))
		{
			motor[intake] = 75;
		}
		else if(joy2Btn(8))
		{
			motor[intake] = -75;
		}
		else
		{
			motor[intake] = 0;
		}
		//Buttons 6 and 8 Control Intake

		if( joy2Btn(4) )//open
		{
			servo[drop] = 10;
		}
		else if(joy2Btn(3))
		{//close
			servo[drop] = 100;
		}
	}
}
