#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheel1,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel2,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     leftWheel1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     leftWheel2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    front,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    back,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    lift1,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    lift2,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void accelChk(int targetSpeed){
	int startSpeed=0;
	int right1=motor[rightWheel1];
	int right2=motor[rightWheel2];
	int left1=motor[leftWheel1];
	int left2=motor[leftWheel2];
	startSpeed= (right1+right2+left1+left2)/4;//this should usually be called when startSpeed ~0
	//int timeTaken=(targetSpeed-startSpeed);
	for(int speed=startSpeed;speed<targetSpeed; speed+=20){
		nxtDisplayBigStringAt(1, 1, "this is working");
    motor[rightWheel1]=speed;
		motor[rightWheel2]=speed;
		motor[leftWheel1]=speed;
		motor[leftWheel2]=speed;
		wait1Msec(10);
	}
}
	task main(){
accelChk(100);
}
