#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheel1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     leftWheel1,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     leftWheel2,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    s1,                   tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    s2,                   tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    s3,                   tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    s4,                   tServoStandard)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  // include file to "handle" the Bluetooth messages.

void initializeRobot() {
  return;
}

task main()
{
  bDisplayDiagnostics = false; // don't have dumb display
  servo[s3] = 0; servo[s4] = 250; // set score servos to same value
	motor[leftWheel1] = 50;
  motor[leftWheel2] = 50;
  motor[rightWheel1] = 50;
  motor[rightWheel2] = 50; //all motors spin forever at 50 power.
  while (true)//always run
  {
  	for(int i = 1; i < 4; i++)//cycle between servos to test
  	{
  		if(i == 1){ servo[s1] = 250; wait1Msec(500); servo[s1] = 0; }; //front servo
  		if(i == 2){ servo[s2] = 250; wait1Msec(500); servo[s2] = 0; }; //back servo
  		if(i == 3){ servo[s3] = 0; servo[s4] = 250; wait1Msec(500); servo[s3] = 250; servo[s4] = 0; };//ball score servo
			PlaySound(soundBeepBeep);//beeps
  		wait1Msec(2000);//waits for 2 seconds
 		}
  }
}
